### ISSUE TITLE
Write all HTML views in Slim

### ISSUE THREAD

**Issue by anhpnguyen** [anhpnguyen/tc359_rails_final#2]
@chrisvfritz hi Chris! I get an error "unexpected end of line" in stories/index.html.slim line 22. Can you help me? Also when do we use double or single equal sign in front of operation "render"?

**Comment by anhpnguyen** [comment]
@chrisvfritz i accidentally missed the "v" in your github name. That's why you didn't get my message...:(

**Comment by chrisvfritz** [comment]
Ahh. :smiley: The error is probably coming from [this line](https://github.com/anhpnguyen/tc359_rails_final/blob/master/app/views/stories/index.html.slim#L12). You have an `if` statement, but nothing inside of it. You probably want to indent the lines beneath it if you only want them to show up if that statement is true.

As for `==` vs `=`, [check out these docs](https://github.com/slim-template/slim#output-) for an explanation of the difference.

**Comment by anhpnguyen** [comment]
Hi Chris! I'm still getting the same error even though I indented
everything that goes after conditional statements. Can you give me some
inputs?

**Comment by anhpnguyen** [comment]
I also have a question about a decision I have to make for my internship
this summer. I'm wondering if you can give me some ideas. So let me know if
you have time for it.

Thank you.

**Comment by chrisvfritz** [comment]
> I'm still getting the same error even though I indented everything that goes after conditional statements.

I just took a closer look and it seems there are quite a few problems:
- There's a [missing closing quote here](https://github.com/anhpnguyen/tc359_rails_final/blob/master/app/views/stories/index.html.slim#L2).
- Another [missing closing quote here](https://github.com/anhpnguyen/tc359_rails_final/blob/master/app/views/layouts/application.html.slim#L8).
- [These lines](https://github.com/anhpnguyen/tc359_rails_final/blob/master/app/views/stories/index.html.slim#L8-L11) are double-indented.

There are some other problems I see that aren't causing errors, but I think it stems from misunderstanding this one point: indention matters a lot in Slim. For example, if I want a `p` tag inside of a `div` with a class of `container`, I will do this:

``` slim
.container
  p This is the stuff in the p tag.
```

If I don't indent the `p` tag, those elements will be next to each other, rather than inside of the other. If I indent too much, I'll get an error. Let me know if that makes sense.

> I also have a question about a decision I have to make for my internship
> this summer. I'm wondering if you can give me some ideas. So let me know if
> you have time for it.

I definitely have time for it! Since it's more personal, just shoot me a separate email and I'll be happy to help however I can.

**Comment by anhpnguyen** [comment]
Thanks Chris! I fixed it. I guess I use slim from now haha.

**Comment by chrisvfritz** [comment]
:smiley: Did you push your changes to GitHub? It looks like those problems still exist in the current code.

**Comment by anhpnguyen** [comment]
Sorry. I just did!

**Comment by chrisvfritz** [comment]
:+1: Looks good!
